version: "3.8"
services:
  taoswabot:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    network_mode: host
    restart: "unless-stopped"
    volumes:
      - ./:/app
